### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by richfitz** [gaborcsardi/progress#12]
I'd like to use this, but am concerned that it might be a bit slow for general use.  A really simple profile:

```r
Rprof()
for (i in 1:10) {
  pb <- progress_bar$new(total = 100)
  for (j in 1:100) {
    pb$tick()
  }
}
Rprof(NULL)
```

I see about 5s to to the thousand ticks here, which seems far too much.  The top few culprits for total time:

```
                    total.time total.pct self.time self.pct
"<Anonymous>"             5.00     100.0      0.02      0.4
"pb_tick"                 5.00     100.0      0.00      0.0
"pb_render"               4.92      98.4      0.00      0.0
"%>%"                     2.46      49.2      0.04      0.8
"isatty"                  2.28      45.6      2.28     45.6
"is_supported"            2.28      45.6      0.00      0.0
"cursor_to_start"         2.12      42.4      0.00      0.0
"eval"                    1.34      26.8      0.16      3.2
"split_chain"             1.26      25.2      0.16      3.2
"freduce"                 1.04      20.8      0.04      0.8
"withVisible"             1.04      20.8      0.02      0.4
"_fseq"                   1.04      20.8      0.00      0.0
"Recall"                  1.00      20.0      0.00      0.0
"as.list"                 0.72      14.4      0.48      9.6
"%s%"                     0.66      13.2      0.00      0.0
"pretty_bytes"            0.62      12.4      0.02      0.4
"is_first"                0.52      10.4      0.02      0.4
```

presumably `is_supported` is used for can be done at progress bar creation and cached.  It looks like the overhead from chaining is also consuming a decent amount of time.

**Comment by gaborcsardi** [comment]
Sorry, closed accidentally. 

I agree completely, and I'll speed it up. I'll even add a C++ API if that is possible at all.

**Comment by gaborcsardi** [comment]
Interestingly, caching the result of `is_supported()` does not make it any faster. :(

**Comment by gaborcsardi** [comment]
The default format is now much faster. This is still slower than I would like it to be, but it seems that the slow part is `cat()` now, and that is not straightforward to improve. Maybe if I could do the cat from C, that would help. Anyway, I'll close this now, and open another issue for a C/C++ API.

**Comment by gaborcsardi** [comment]
Btw. is this fast enough for you?

**Comment by gaborcsardi** [comment]
Now it takes about 40-50 ms for 100 ticks, with the default format, which might be acceptable, if you run something that takes at least a couple of seconds. 

Btw. how about some limit parameter for showing the progress bar at all? E.g. only showing it after half a second?

**Comment by richfitz** [comment]
Yeah, I was thinking I should have benchmarked cat to get an idea of how long you'd *expect* - printing to screen can be surprisingly slow.  Thanks for fixing this so quickly!

I think the relate limiting for showing the bar is a good idea, so long as the overhead doesn't exceed the savings

**Comment by sahilseth** [comment]
How does this compare with https://stat.ethz.ch/R-manual/R-devel/library/utils/html/txtProgressBar.html in terms of speed?

I really like the idea of showing ETA etc.

Also in a few cases of mine the loop is extremely long (4 million +). Doing a computation and updating the bar every at every 1000th tick is better? What would you recommend.

**Comment by gaborcsardi** [comment]
Why don't you try? :) Look at the microbenchmark package.

As for the number of ticks, it is probably not worth doing more than 100, because the display is probably shorter than that.

ps. please open a new issue next time. I don't look at closed issues like this one, so unless I reply immediately, I'll probably forget to reply. Thanks.
