### ISSUE TITLE
tick with len = 0

### ISSUE THREAD

**Issue by richfitz** [gaborcsardi/progress#15]
I have a use case combined with custom tags for advancing a progress bar by zero units, but this is currently disallowed

```
pb <- progress::progress_bar$new()
pb$tick(0)
```

I tried removing the [assertion](https://github.com/gaborcsardi/progress/blob/master/R/progress.r#L216) but ran into another bit of trouble with the time estimation code, even though I was not using estimation (sorry don't have the traceback handy).

In case you're wondering, I want to have a small ascii spinning wheel tick over periodically when there are no results retuned.  However, I can imagine more general cases where allowing negative increments could actually make sense...

**Comment by gaborcsardi** [comment]
Yes, I agree completely, this should work.

**Comment by gaborcsardi** [comment]
For example `tick(0)` could be used instead of a `begin()` method.

**Comment by gaborcsardi** [comment]
OK, should be good now. I should really write some tests, but not easy to test progress bars.....
