### ISSUE TITLE
show_after doesn't stop progress bars from being showed

### ISSUE THREAD

**Issue by jefferis** [gaborcsardi/progress#33]
It just stops them from being updated. Is this the expected behaviour?

For example on my machine, this shows a progress bar with 1 tick, waits 1s and then starts updating it.
```
pb <- progress_bar$new(total = 100, show_after=1)
for (i in 1:100) {
    pb$tick()
    Sys.sleep(2 / 100)
}
```

Or here the progress bar is shown, when I would not expect it to be shown.
```
pb <- progress_bar$new(total = 100, show_after=1)
for (i in 1:100) {
    pb$tick()
    Sys.sleep(0.01 / 100)
}
```

I see that commit 532715f533ff630d6243c945efbdd54952b85422 added a relevant test, but the expectation does not seem to match the description `"very quick loops, only the result is shown"`. Thanks for clarifying!

**Comment by gaborcsardi** [comment]
Yes, I agree it is confusing. The problem is that even if you say that you want the progress bar after one second, you might not get a tick for a minute, and then nothing is shown for a minute. I thought that it is better to show at least the progress bar, then.

But you can convince me that it is better to show nothing, I am really not sure.

**Comment by jefferis** [comment]
> Yes, I agree it is confusing. The problem is that even if you say that you want the progress bar after one second, you might not get a tick for a minute, and then nothing is shown for a minute. 
> 
I presume there is no way to show an empty bar without a tick after the delay.
> I thought that it is better to show at least the progress bar, then.
> 
> But you can convince me that it is better to show nothing, I am really not sure.
> 

I think it is better to show nothing until the delay has elapsed. You could always add an extra arg for this. Or differentiate between a user specified show_after and a default show_after. 

On a related note when the bar is cleared there is an extra blank line left behind for me in Rstudio but not in R running in the terminal. Do you see this?

**Comment by gaborcsardi** [comment]
> I think it is better to show nothing until the delay has elapsed. 

OK.

> On a related note when the bar is cleared there is an extra blank line left behind for me in Rstudio but not in R running in the terminal. Do you see this?

There is no way to clear that line in RStudio, AFAIK.
